name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'

      - name: Install dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libvpx7 \
            libevent-2.1-7 \
            libflite1 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-video1.0-0 \
            libgstreamer-fft1.0-0 \
            libgstreamer-pbutils1.0-0 \
            libgstreamer-audio1.0-0 \
            libgstreamer-tag1.0-0 \
            libharfbuzz-icu0 \
            libhyphen0 \
            libgles2-mesa \
            x264

      - name: Install Maven Dependencies
        run: mvn install -DskipTests

      - name: Run Playwright Tests
        run: xvfb-run --auto-servernum -- mvn test

      - name: Generate Test Report
        run: mvn surefire-report:report

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports
